# -*- coding: utf-8 -*-
"""lab_ordenlicher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGqUA7bwywvo_1xOPRg9ZRdTnKiUzrCa
"""

import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from math import pi
from numpy import radians, degrees, sin, cos, arccos, sqrt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize
from matplotlib.animation import PillowWriter
from matplotlib.animation import FuncAnimation, FFMpegWriter
import matplotlib.animation as animation
import matplotlib as mpl
mpl.rcParams['animation.embed_limit'] = 120  # Erhöhe das Limit auf 50 MB
from numba import njit
import scipy.interpolate
from scipy.integrate import solve_ivp
from scipy.interpolate import SmoothBivariateSpline
from scipy.interpolate import RBFInterpolator

# from google.colab import files #upload von unseren datensätzen
# uploaded = files.upload()

# Hydrogen data
data_h_raw = pd.read_csv(
    "apjs504506t2_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_H_raw", "T_H_raw", "p_H_raw", "E_H_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_h_log = pd.DataFrame({
    "rho_H": np.log(data_h_raw["rho_H_raw"] * 1000), #[kg/m^3]
    "T_H": np.log(data_h_raw["T_H_raw"]),
    "p_H": np.log(data_h_raw["p_H_raw"] * 1e9), #[Pa]
    "E_H": np.log(data_h_raw["E_H_raw"] * 1e6 + 1.6e9)
}) #.dropna()

E_H_raw = data_h_raw["E_H_raw"] * 1e6
p_H_raw = data_h_raw["p_H_raw"] * 1e9
T_H_raw = data_h_raw["T_H_raw"]
rho_H_raw = data_h_raw["rho_H_raw"] * 1000
#print(data_h_raw)

# Extract cleaned numpy arrays
rho_H = data_h_log["rho_H"].to_numpy()
T_H = data_h_log["T_H"].to_numpy()
p_H = data_h_log["p_H"].to_numpy()
E_H = data_h_log["E_H"].to_numpy()

Tp_H = np.column_stack((T_H, p_H))
rhoT = np.column_stack((T_H, rho_H))
rhoT_raw = np.column_stack((T_H_raw, rho_H_raw))
Tp_H_raw = np.column_stack((T_H_raw, p_H_raw))

# Helium data
data_he_raw = pd.read_csv(
    "apjs504506t3_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_He_raw", "T_He_raw", "p_He_raw", "E_He_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_he_log = pd.DataFrame({
    "rho_He": np.log(data_he_raw["rho_He_raw"] * 1000),
    "T_He": np.log(data_he_raw["T_He_raw"]),
    "p_He": np.log(data_he_raw["p_He_raw"] * 1e9),
    "E_He": np.log(data_he_raw["E_He_raw"] * 1e6 + 1.6e9)
}) #.dropna()

E_He_raw = data_he_raw["E_He_raw"] * 1e6
p_He_raw = data_he_raw["p_He_raw"] * 1e9
T_He_raw = data_he_raw["T_He_raw"]
rho_He_raw = data_he_raw["rho_He_raw"] * 1000

# Extract cleaned numpy arrays
rho_He = data_he_log["rho_He"].to_numpy()
T_He = data_he_log["T_He"].to_numpy()
p_He = data_he_log["p_He"].to_numpy()
E_He = data_he_log["E_He"].to_numpy()

Tp_He = np.column_stack((T_He, p_He))
rhoT_He = np.column_stack((T_He, rho_He))
Tp_He_raw = np.column_stack((T_He_raw, p_He_raw))
rhoT_He_raw = np.column_stack((T_He_raw, rho_He_raw))

interpolator = scipy.interpolate.LinearNDInterpolator(Tp_H, rho_H) # Hydrogen
interpolatorHe = scipy.interpolate.LinearNDInterpolator(Tp_He, rho_He) #He

interpolatorENer = scipy.interpolate.LinearNDInterpolator(rhoT_raw, E_H_raw)
interpolatorENerHe = scipy.interpolate.LinearNDInterpolator(rhoT_He_raw, E_He_raw)

#paramerter:
G = 6.674e-11
h = 1e-3

dE_dT_H = (
    interpolatorENer(T_H_raw + h, rho_H_raw)
    - interpolatorENer(T_H_raw, rho_H_raw)
) / (h)

dE_drho_H = (
    interpolatorENer(T_H_raw, rho_H_raw + h)
    - interpolatorENer(T_H_raw, rho_H_raw)
) / (h)

interpolator_dE_dT_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H_raw, rho_H_raw)),
    dE_dT_H
)
interpolator_dE_drho_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H_raw, rho_H_raw)),
    dE_drho_H
)


dE_dT_He = (
    interpolatorENerHe(T_He_raw + h, rho_He_raw)
    - interpolatorENerHe(T_He_raw, rho_He_raw)
) / (h)
dE_drho_He = (
    interpolatorENerHe(T_He_raw, rho_He_raw + h)
    - interpolatorENerHe(T_He_raw, rho_He_raw)
) / (h)

interpolator_dE_dT_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He_raw, rho_He_raw)),
    dE_dT_He
)
interpolator_dE_drho_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He_raw, rho_He_raw)),
    dE_drho_He
)

def drho_dT_H3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogT = (
        interpolator(logT + h, logp)
        - interpolator(logT, logp)
    ) / h

    return (rhoo / T_) * dlogrho_dlogT

def drho_dT_He3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogT = (
        interpolatorHe(logT + h, logp)
        - interpolatorHe(logT, logp)
    ) / h

    return (rhoo / T_) * dlogrho_dlogT

def drho_dp_H3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogp = (
        interpolator(logT, logp + h)
        - interpolator(logT, logp)
    ) / h

    return (rhoo / p_) * dlogrho_dlogp

def drho_dp_He3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogp = (
        interpolatorHe(logT, logp + h)
        - interpolatorHe(logT, logp)
    ) / h

    return (rhoo / p_) * dlogrho_dlogp

"""# Radiusfunktion"""

def find_radius_profile(density, mass_profile):
  ''' INPUT:
      density = constant value or array of values
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT looks like
      r_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... ,[rN-1lower, rN-1, rN-1upper], [rNlower, rN, rNupper]]
      '''

  N = len(mass_profile)
  r_profile = np.zeros((N,3))
  if type(density) not in [np.ndarray, list]:
    density = np.full(N, density)

  rilower = 0

  for i in range(0,N): #stops @ N-1 (index of shell N is N-1)
    r_profile[i][0] = rilower
    riupper = np.cbrt(3*mass_profile[i]/(4*np.pi*density[i]) + rilower**3)
    r_profile[i][2] = riupper
    r_profile[i][1] = (rilower + riupper)/2 #STEP 3
    rilower = riupper

  return r_profile

"""# Pressure function"""

def find_pressure_profile(radius_profile, mass_profile):
  ''' INPUT:
      radius_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... , [rNlower, rN, rNupper]]
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT should look like
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]'''

  N = len(radius_profile)
  if len(mass_profile) != N:
    raise ValueError("mass_profile and radius_profile must have the same length")

  p_profile = np.zeros((N,3))

  p_profile[-1][2] = 100000

  for i in range(N-1,0,-1): #starts @ N-1 (index of shell N) and goes down to 1 (index of shell 2)
    dp = G/(4*np.pi)*np.sum([mass_profile[k] for k in range(i)])*mass_profile[i]/radius_profile[i][1]**4 #FORMULA (17)
    p_profile[i][0] = p_profile[i][2] + dp
    p_profile[i-1][2] = p_profile[i][0]

    # geometric mean (more stable)
    p_profile[i][1] = np.sqrt(p_profile[i][0]*p_profile[i][2])
    # arithmetic mean
    # p_profile[i][1] = (p_profile[i][0]+p_profile[i][2])/2 #FORMULA (16)

  #afterwards special treatment for i=0 (shell 1) [0, 0, r1upper]
  p_profile[0][0] = p_profile[0][2] + 3*G*mass_profile[0]**2/(8*np.pi*radius_profile[0][2]**4) #deltar1 FORMULA (19)
  p_profile[0][1] = (p_profile[0][0]+p_profile[0][2])/2

  return p_profile

"""# Temperatur function"""

def find_T_profile(pressure_profile, eos_profile, density_profile, T_0):
  p_profile = pressure_profile[:, 2]

  T_profile = np.zeros_like(p_profile)
  T_profile[-1] = T_0

  for i in range(len(p_profile)-1, 0, -1):
      

      T = T_profile[i]
      p = p_profile[i]

      if eos_profile[i]['eos'] == 'h':
          # hydrogen
          rho = calc_density_eos(p, T, interpolator)
          dEdT = interpolator_dE_dT_H(np.column_stack((T, rho)))[0]
          dEdrho = interpolator_dE_drho_H(np.column_stack((T, rho)))[0]
          drhodT = drho_dT_H3(T, p, rho)
          drhodp = drho_dp_H3(T, p, rho)

      else:
          # Helium
          rho = calc_density_eos(p, T, interpolatorHe)
          dEdT = interpolator_dE_dT_He(np.column_stack((T, rho)))[0]
          dEdrho = interpolator_dE_drho_He(np.column_stack((T, rho)))[0]
          drhodT = drho_dT_He3(T, p, rho)
          drhodp = drho_dp_He3(T, p, rho)

      dTdp = -drhodp / (drhodT + dEdT/(dEdrho - p/rho**2))
      dp = p_profile[i-1] - p
      dT = dTdp * dp

      # standard, linear version
      # T_profile[i-1] = T + max(dT, 0)
      # log-integrated alternative (which gives a factor rather than an addend)
      T_profile[i-1] = T*(p_profile[i-1]/p)**(p/T*max(dTdp,0))

  return T_profile

def find_gamma_profile(pressure_profile, eos_profile, density_profile, T_profile):

  p_profile = pressure_profile[:, 2]

  gamma_profile = np.zeros_like(p_profile)

  for i in range(len(p_profile)-1, -1, -1):

    T = T_profile[i]
    p = p_profile[i]
    rho_val = density_profile[i]

    if eos_profile[i]['eos'] == 'h':
      # hydrogen
      dE_dT_val = interpolator_dE_dT_H(np.column_stack((T, rho_val)))[0]
      dE_drho_val = interpolator_dE_drho_H(np.column_stack((T, rho_val)))[0]
      drho_dT_val = drho_dT_H3(T, p, rho_val)
      drho_dp_val = drho_dp_H3(T, p, rho_val)

      dTdp = - drho_dp_val / (drho_dT_val + dE_dT_val * (dE_drho_val - p/rho_val**2)**(-1))

    else:
      # Helium
      dE_dT_vale = interpolator_dE_dT_He(np.column_stack((T, rho_val)))[0]
      dE_drho_vale = interpolator_dE_drho_He(np.column_stack((T, rho_val)))[0]
      drho_dT_vale = drho_dT_He3(T, p, rho_val)
      drho_dp_vale = drho_dp_He3(T, p, rho_val)

      dTdp = - drho_dp_vale / (drho_dT_vale + dE_dT_vale * (dE_drho_vale - p/rho_val**2)**(-1))

    gamma_profile[i] = 1 / (1 - dTdp * p/T)
    
  return gamma_profile

def find_gammaH_profile(pressure_profile, density_profile, T_profile):

  p_profile = pressure_profile

  gamma_profile = np.zeros_like(p_profile)

  for i in range(len(p_profile)-1, -1, -1):

      T = T_profile[i]
      p = p_profile[i]
      rho_val = density_profile[i]

      dE_dT_val = interpolator_dE_dT_H(np.column_stack((T, rho_val)))[0]
      dE_drho_val = interpolator_dE_drho_H(np.column_stack((T, rho_val)))[0]
      drho_dT_val = drho_dT_H3(T, p, rho_val)
      drho_dp_val = drho_dp_H3(T, p, rho_val)

      dTdpH = - drho_dp_val / (drho_dT_val + dE_dT_val * (dE_drho_val - p/rho_val**2)**(-1))

    # Helium
      dE_dT_vale = interpolator_dE_dT_He(np.column_stack((T, rho_val)))[0]
      dE_drho_vale = interpolator_dE_drho_He(np.column_stack((T, rho_val)))[0]
      drho_dT_vale = drho_dT_He3(T, p, rho_val)
      drho_dp_vale = drho_dp_He3(T, p, rho_val)

      dTdpHe = - drho_dp_vale / (drho_dT_vale + dE_dT_vale * (dE_drho_vale - p/rho_val**2)**(-1))

    # Materialwahl

      dTdp = dTdpH #dTdpHe if eos_profile[i]['eos'] != 'h' else dTdpH

      gamma_profile[i] = 1 / (1 - dTdp * p/T)
  return gamma_profile

gamm = find_gammaH_profile(p_H_raw, rho_H_raw, T_H_raw)
np.set_printoptions(threshold=np.inf)
# print(np.column_stack((rho_H_raw, T_H_raw, p_H_raw, gamm)))
np.savetxt("gammaH.txt",np.column_stack((rho_H_raw, T_H_raw, p_H_raw, gamm)))

"""# density profile iterativ"""

def keywords_check(dictionary, index, *keywords):
    missing = [key for key in keywords if key not in dictionary]

    if missing:
        raise ValueError(
            f"Missing keywords {missing} in Shell with index {index}!"
        )

def create_eos_profile(layers_def):
    '''INPUT Example:

    layer_definitions_example = [
    {
        'eos_type': 'rocky',
        'params': {'k_0': 200e9, 'k_d': 3.5, 'rho_0': 5500},
        'num_layers': 50 # 50 layers for the rocky core
    },
    {
        'eos_type': 'h',
        'params': {'temperature': 100000}, # Assuming a constant temperature for this hydrogen section
        'num_layers': 50 # 50 layers for the hydrogen shell
    }
]

    OUTPUT should be a list of dictionaries.
  '''
    full_eos_profile=[]

    for layer_dict in layers_def:
        eos_type = layer_dict['eos_type']
        if 'params' in layer_dict:
            params_dict = layer_dict['params']
        n_layers = layer_dict['num_layers']
        for _ in range(n_layers):
            layer={'eos': eos_type}
            layer.update(params_dict)
            full_eos_profile.append(layer)

    return full_eos_profile

def rocky_eos(pressure, K_0, K_d, rho_0):
    if hasattr(pressure, "ndim") and pressure.ndim > 1:
        P = pressure[:, 1]
    else:
        P = pressure
    return rho_0*(1+K_d*P/K_0)**(1/K_d)

def calc_density_eos(pressure, T, interp = interpolator, log_x_interp=True):
    """Berechnet das Dichteprofil mithilfe einer Zustandsgleichung (EOS) gegeben durch den Interpolator.

    Die Funktion wertet einen Interpolator basierend auf der Temperatur und dem
    Druck aus. Sie ist flexibel und akzeptiert sowohl einzelne Skalarwerte als
    auch Arrays. Falls ein 2D-Druckprofil übergeben wird, extrahiert sie
    automatisch die relevante Druckspalte.

    Parameters
    ----------
    pressure : float, array_like of shape (N,) or (N, 3)
        Das Druckprofil. Kann eine einzelne Zahl (Skalar), ein 1D-Array
        oder ein 2D-Array mit 3 Spalten sein (hierbei wird die 2. Spalte mit Index 1 genutzt).
        Einheit der Eingabe: Pascal (Pa).
    T : float or array_like of shape (N,)
        Das Temperaturprofil in Kelvin (K). Muss dieselbe Länge wie
        `pressure` haben, wenn Arrays übergeben werden.
    interp : callable
        Die Interpolationsfunktion (z. B. für Wasserstoff oder Helium).
        Erwartet eine Liste/ein Array mit ``[T, P]`` und
        gibt ein Array zurück, dessen erstes Element [0] den Dichtewert enthält.

    Returns
    -------
    density_profile : float or ndarray of shape (N,)
        Die berechnete Dichte in kg/m³. Gibt einen einzelnen Skalar zurück,
        wenn die Eingaben Skalare waren, andernfalls ein Array.

    Raises
    ------
    ValueError
        Wenn `T` und `pressure_profile` als Arrays übergeben werden,
        aber nicht die gleiche Länge haben.
    """
    is_iterable = hasattr(pressure, "__len__") or hasattr(T, "__len__")

    if is_iterable:
        P = np.asarray(pressure)
        T = np.asarray(T)

        N = len(pressure)
        if len(T) != N:
            raise ValueError("T and pressure_profile must have the same length")

        P = P[:,1] if P.ndim > 1 else P

        if log_x_interp:
            density_profile = np.exp(interp(np.log(T), np.log(P)))
        else:
            density_profile = np.exp(interp(T, P))

        return density_profile
    else:
        P = np.asarray(pressure)
        P = P[:,1] if P.ndim > 1 else P
        T = np.asarray(T)
        if log_x_interp:
            density_profile = np.exp(interp(np.log(T), np.log(P)))
        else:
            density_profile = np.exp(interp(T, P))

        return density_profile

def density_from_eos_profile(pressure_profile, temperature, eos_profile, interpH=interpolator, interpHe=interpolatorHe, **kwargs):
  ''' INPUT:
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]
      temperature = [T1, T2, ..., Tn]
      eos_profile = list of dics. One dictionary for each layer. The keyword 'eos' gives which equation of state to use. "he", "h", "rocky"(then K_0 and K'_0 (called 'k_d') and rho_0 need to be provided).
                    If eos is a list of either ['h', 'he'] or ['rocky_1', 'rocky_2'] then the parameter keyword 'X_H', 'Y_He' or 'M_{1,2}' need to be given

      FUNCTION gives the density from an equation of state. Different Equation of states are given in the eos_profile list of layer dictionaries

      OUTOUT should look like
      density = [rho1, rho2, ..., rhoN]
      '''
  N = len(pressure_profile)
  if N != len(eos_profile):
      raise ValueError('eos_profile needs to be same lenght as pressure_profile')

  if type(temperature) not in [np.ndarray, list]:
    temperature = np.full(N, temperature)
  T = np.array(temperature)

  density_profile = np.zeros(N)

  for i, layer_dict in enumerate(eos_profile):
      eos=layer_dict['eos']

      if type(eos) in [list, np.ndarray] and len(eos) >= 2:

          if 'h' in eos and 'he' in eos: # ['h', 'he'] and ['he', 'h']
            density_H = calc_density_eos(pressure_profile[i][1], T[i], interp=interpH)
            density_He = calc_density_eos(pressure_profile[i][1], T[i], interp=interpHe)
            keywords_check(layer_dict, i, "X_H", "Y_He")
            density_profile[i] = ((layer_dict['X_H'])/(density_H) + (layer_dict['Y_He']/(density_He)))**(-1) # see formula (1) in Miguel+2016 for mix

          elif 'rocky_1' in eos and 'rocky_2' in eos: # ['rocky_1', 'rocky_2']

            keywords_check(layer_dict, i,  "k_0_1", "k_d_1", "rho_0_1", "M_1", "k_0_2", "k_d_2", "rho_0_2", "M_2")
            density_1 = rocky_eos(pressure_profile[i][1], layer_dict['k_0_1'], layer_dict['k_d_1'], layer_dict['rho_0_1'])
            density_2 = rocky_eos(pressure_profile[i][1], layer_dict['k_0_2'], layer_dict['k_d_2'], layer_dict['rho_0_2'])
            density_profile[i] = ((layer_dict['M_1'])/(density_1) + (layer_dict['M_2'])/(density_2))**(-1)

        # other mixture possibilities?

      elif type(eos)==str or len(eos)==1:
          if type(eos) in [list, np.ndarray] and len(eos)==1:
              eos = eos[0] # just to be sure
          #single eos, so no mixture
          if eos == "he":
              density_profile[i] = calc_density_eos(pressure_profile[i][1], T[i], interp=interpHe)
          elif eos == "h":
              density_profile[i] = calc_density_eos(pressure_profile[i][1], T[i], interp=interpH)
          elif eos == "rocky":
              keywords_check(layer_dict, i, "k_0", "k_d", "rho_0")

              K_0 = layer_dict['k_0']
              K_d = layer_dict['k_d']
              rho_0 = layer_dict['rho_0']
              density_profile[i] = rocky_eos(pressure_profile[i][1], K_0, K_d, rho_0)
          else:
              raise ValueError(f"Unknown equation of state: {eos} in shell with index {i}! One string was detected.")
      else:
          raise ValueError(f"Unknown equation of state: {eos} in shell with index {i}! It either needs to be a string, e.g. 'h', 'he' or 'rocky', or a list of strings (['h', 'he'], ['he', 'h'] or ['rocky_1', 'rocky_2'] for a mixture.")
  return density_profile

def one_cycle_var(mass_profile, first_density, temperature, eos_profile, **kwargs):
  ''' INPUT:
      mass_profile = [m1,m2,m3,..., mN]
      first_density = constant value or array of values
      temperature = [T1, T2, ..., Tn]
      eos_profile = {first transition: 'eos_below_first_transition',
                     second transition: 'eos_between_first_and_second_transition',
                     ...}
      FUNCTION represents one cycle

      OUTPUT should look like
      new_density = [[rho1lower, rho1, rho1upper], [rho2lower, rho2, rho2upper], ..., [rhoNlower, rhoN, rhoNupper]]
      '''

  r_profile = find_radius_profile(first_density, mass_profile) #RADIUS
  p_profile = find_pressure_profile(r_profile, mass_profile) #PRESSURE

  new_density = density_from_eos_profile(p_profile, temperature, eos_profile, **kwargs) #EQUATION OF STATE

  temp_profile = find_T_profile(p_profile, eos_profile, new_density, temperature[-1], **kwargs)

  return r_profile, p_profile, new_density, temp_profile

def create_mass_profile(mass_total, N, profile='constant'):
  if profile == 'constant':
    mass_profile = np.full(N, mass_total / N)
  elif profile == 'linear':
    mass_profile = np.linspace(mass_total / N, mass_total, N)
  # add more mass distribution profiles?
  return mass_profile

def create_temp_profile(T, N, profile='constant'):
  if profile == 'constant':
    T_profile = np.full(N, T)
  elif profile == 'linear':
    T_profile = np.linspace(T, 0, N) #this does not make sense right?
  return T_profile

def create_density_profile(rho, N, profile='constant'):
  if profile == 'constant':
    density_profile = np.full(N, rho)
  elif profile == 'linear':
    density_profile = np.linspace(rho, 0, N)
  return density_profile

################################################################################

def multi_iteration(starting_density, mass_total, N, T, eos_profile, mass_profile=None,
                    mass_distro_profile='constant', temp_distro_profile='constant',
                    density_distro_profile='constant', tolerance=1e-6, max_iter=20,
                    quiet=True, print_iter=2, **kwargs):
  if mass_profile==None:
    mass_profile = create_mass_profile(mass_total, N, profile=mass_distro_profile)
  else:
    mass_profile = np.array(mass_profile)

  if type(T) in [np.ndarray, list]:
    T = T
  else:
    T = create_temp_profile(T, N, profile=temp_distro_profile)

  if type(starting_density) in [np.ndarray, list]:
    rho = starting_density
  else:
    rho = create_density_profile(starting_density, N, profile=density_distro_profile)

  for iteration in range(max_iter):
    r_profile, p_profile, new_rho, temp_profile = one_cycle_var(mass_profile, rho, T, eos_profile, **kwargs)

    rel_diff = abs(new_rho[0] - rho[0]) / rho[0]

    # if quiet == False: #and iteration >= max_iter-print_iter:
    print(f"Relative Änderung bei Iteration {iteration+1:3d}: {rel_diff:.3e}, T[0] = {T[0]:9.2f} K, R = {r_profile[-1][2]/1e3:9.2f} km")

    # Abbruchbedingung
    if rel_diff < tolerance:
      if quiet == False:
        print("\nKonvergenz erreicht.")
      break

    # neues Profil übernehmen
    rho = new_rho.copy()
    T = temp_profile.copy()

  if quiet == False:
    print("\nFinales Radiusprofil:")
    print(r_profile)

    print("\nFinales Druckprofil:")
    print(p_profile)

    print("\nFinales Dichteprofil:")
    print(new_rho)

    print("\nFinales Temperaturprofil:")
    print(temp_profile)

  return r_profile, p_profile, new_rho, temp_profile

"""# Example:

## Jupyter:
"""

#jupyter:

'''rho_0 = 1249.5 kg/m^3
K_0 = 4.26 GPa
K_0' = 7.75

Perovskite
rho_0 4105.9
K_0 = 270.6
K_0' = 3.81
'''

# layers_def = [
#     {
#         'eos_type': 'rocky',
#         'params': {'k_0': 270.6e9, 'k_d': 3.81, 'rho_0': 4105.9},
#         'num_layers': 2 # 50 layers for the rocky core
#     },
#     {
#         'eos_type': 'he',
#         'params': {},
#         'num_layers': 10 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': 'h',
#         'params': {},
#         'num_layers': 90 # 50 layers for the hydrogen shell
#     }
# ]

layers_def = [
    {
        'eos_type': 'rocky',
        'params': {'k_0': 270.6e9, 'k_d': 3.81, 'rho_0': 4105.9},
        'num_layers': 80 # 50 layers for the rocky core
    },
    {
        'eos_type': 'he',
        'params': {},
        'num_layers': 400 # 50 layers for the hydrogen shell
    },
    {
        'eos_type': 'h',
        'params': {},
        'num_layers': 3600 # 50 layers for the hydrogen shell
    }
]

eos_profile = create_eos_profile(layers_def)

N = len(eos_profile)

mass_total = 1.898e27 #kg

rho_0 = 1300 #kg/m^3

T_0 = 365

r_profile, p_profiile, rho_profile, tmp_profile = multi_iteration(rho_0, mass_total, N, T_0, eos_profile, quiet=True, max_iter = 40)

gamma_prof = find_gamma_profile(p_profiile, eos_profile, rho_profile, tmp_profile)

# print(gamma_prof[12])
# print(gamma_prof)
#(H_2: 1.4, He:1.66)

# """## Asteroid - Ceres"""
# 
# '''rho_0 = 1249.5 kg/m^3
# K_0 = 4.26 GPa
# K_0' = 7.75
# 
# Hydrated Silicate Mixture (ChatGPT):
# 
# rho = 2200-2800
# K_0 = 20-70
# K_0' = 4-7
# '''
# 
# layers_def = [
#     {
#         'eos_type': 'rocky',
#         'params': {'k_0': 50e9, 'k_d': 6, 'rho_0': 2500},
#         'num_layers': 50 # 50 layers for the rocky core
#     },
#     {
#         'eos_type': 'rocky',
#         'params': {'k_0': 4.26e9, 'k_d': 7.75, 'rho_0': 1249.5},
#         'num_layers': 10 # 50 layers for the rocky core
#     }
# 
# ]
# 
# eos_profile = create_eos_profile(layers_def)
# 
# N = len(eos_profile)
# 
# mass_total = 9.38392e20 #kg
# 
# rho_0 = 1300 #kg/cm^3
# 
# T_0 = 300
# 
# r_profile, p_profile, rho_profile, tmp_profile = multi_iteration(rho_0, mass_total, N, T_0, eos_profile, quiet=False, max_iter = 40)
# 
# #Zentraldruck:
# R = 469700 #[m]
# radius = r_profile[-1,-1]
# 
# P = 3/2 * G * mass_total**2 /(4* np.pi * R**4)
# P_prof = 3/2 * G * mass_total**2 /(4* np.pi * radius**4)
# 
# print('theoriewert', P)
# print('mit Radiius berechnet', P_prof)
# print('model', p_profile[0,0])
# 
# """# Saturntest
# 
# """
# 
# ''' Aufbau
# 
# Obere Schichten ~96% H_2 ~4% He
# 
# 25% der mass im kern ~12000K temp
# 
# zusammensetzung des kerns Eis-Silikat
# 
# ,
#     {
#         'eos_type': 'he',
#         'params': {},
#         'num_layers': 4
#     }
# '''
# 
# layers_def_saturn = [
#     {
#         'eos_type': 'rocky',
#         'params': {'k_0': 4.26e9, 'k_d': 7.75, 'rho_0': 1249.5},
#         'num_layers': 25
#     },
#     {
#         'eos_type': 'h',
#         'params': {},
#         'num_layers': 75
#     }
# ]
# mass_total_saturn = 5.683e26 # kg
# mean_rho_saturn = 687 # kg/m^3
# 
# eos_profile_sat = create_eos_profile(layers_def_saturn)
# 
# N = len(eos_profile_sat)
# 
# T_0 = 134
# 
# r_profile, p_profiile, rho_profile, tmp_profile = multi_iteration(mean_rho_saturn, mass_total_saturn, N, T_0, eos_profile_sat, quiet=False, max_iter = 40)
# 
# """# Jupiter Mix Test"""
# 
# #jupyter:
# 
# '''rho_0 = 1249.5 kg/m^3
# K_0 = 4.26 GPa
# K_0' = 7.75
# 
# Perovskite
# rho_0 4105.9
# K_0 = 270.6
# K_0' = 3.81
# '''
# 
# layers_def = [
#     {
#         'eos_type': 'rocky',
#         'params': {'k_0': 270.6e9, 'k_d': 3.81, 'rho_0': 4105.9},
#         'num_layers': 2 # 50 layers for the rocky core
#     },
#     {
#         'eos_type': 'he',
#         'params': {},
#         'num_layers': 10 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': ['h', 'he'],
#         'params': {'X_H': 0.1, 'Y_He': 0.9},
#         'num_layers': 5 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': ['h', 'he'],
#         'params': {'X_H': 0.25, 'Y_He': 0.75},
#         'num_layers': 5 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': ['h', 'he'],
#         'params': {'X_H': 0.5, 'Y_He': 0.5},
#         'num_layers': 5 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': ['h', 'he'],
#         'params': {'X_H': 0.75, 'Y_He': 0.25},
#         'num_layers': 5 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': ['h', 'he'],
#         'params': {'X_H': 0.9, 'Y_He': 0.1},
#         'num_layers': 5 # 50 layers for the hydrogen shell
#     },
#     {
#         'eos_type': 'h',
#         'params': {},
#         'num_layers': 80 # 50 layers for the hydrogen shell
#     }
# ]
# 
# 
# eos_profile = create_eos_profile(layers_def)
# 
# N = len(eos_profile)
# 
# mass_total = 1.898e27 #kg
# 
# rho_0 = 1300 #kg/m^3
# 
# T_0 = 160
# 
# r_profile, p_profiile, rho_profile, tmp_profile = multi_iteration(rho_0, mass_total, N, T_0, eos_profile, quiet=False, max_iter = 40)
# 
# """# **Earth Test**
# 
# """
# 
# #earth:
# 
# '''Mechanical STRUCTURE
# - rigid lithosphere
# - semi-fluid astenosphere
# - a rigid mesosphere
# - liquid outer core
# - solid inner core
# 
# Chemical STRUCTURE
# - silicate crust
# - ferromagnesian mantle
# - iron-nickle core
# 
# MATERIALS:
# Silicate:
# 
# Iron: (Wagner+2011)
# rho_0 = 8269.4 kg/m^3
# K_0 = 164.7 GPa
# K_0' = 5.650
# 
# Nickle:
# 
# ice:
# rho_0 = 1249.5 kg/m^3
# K_0 = 4.26 GPa
# K_0' = 7.75
# 
# Perovskite: Wagner+2011 (earth's lower mantle?)
# rho_0 4145
# K_0 = 234 GPa
# K_0' = 4.00
# 
# Iron alloy (wagner+2011; earths outer core?)
# rho_0 = 7488.3 kg/m^3
# K_0 = 169.82 GPa
# K_0' = 4.9835
# 
# Olivine (Wagner+2011)
# rho_0 = 3213.7 kg/m^3
# K_0 = 127.4 GPa
# K_0' = 4.2
# '''
# 
# n_layer = 30
# 
# layers_def = [
#     { #core: iron
#         'eos_type': 'rocky',
#         'params': {'k_0': 164.7e9, 'k_d': 5.650, 'rho_0': 8269.4},
#         'num_layers': n_layer
#     },
#     { # outer core: iron alloy
#         'eos_type': 'rocky',
#         'params': {'k_0': 169.82e9, 'k_d': 4.9835, 'rho_0': 7488.3},
#         'num_layers': n_layer
#     },
#     { #lower mantle: perovskite
#         'eos_type': 'rocky',
#         'params': {'k_0': 234e9, 'k_d': 4.00, 'rho_0': 4145},
#         'num_layers': n_layer
#     },
#     { #upper mantle: olivine
#         'eos_type': 'rocky',
#         'params': {'k_0': 127.7e9, 'k_d': 4.2, 'rho_0': 3213.7},
#         'num_layers': n_layer
#     }
# ]
# 
# eos_profile = create_eos_profile(layers_def)
# 
# N = len(eos_profile)
# 
# mass_total = 5.9722e24 #kg
# 
# rho_0 = 5515 #kg/m^3
# 
# T_0 = 300
# 
# r_profile, p_profiile, rho_profile, tmp_profile = multi_iteration(rho_0, mass_total, N, T_0, eos_profile, quiet=False, max_iter = 40)
# 
# #rho(r) mit verschiedenen oberflchentemp.
# 
# #rho(r) mit verschiedenen materialien(aber gleiches massenverhältnis)
# #rho(r) mit verschiedenem masseverteilung (aber gleiche zusammensetzung)
# surfaceT =np.array([150, 300, 500, 1000, 3000])


def plot_rho_r_temp(surfacetemp, eos_profile, mass_tot, rho_0):






  r = radius[:, 2]
