# -*- coding: utf-8 -*-
"""lab_atmosphere_modelling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhHAMHQrcweV47CXCp-tHf3hSALA9BRQ
"""

import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from math import pi
from numpy import radians, degrees, sin, cos, arccos, sqrt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
from matplotlib.colors import Normalize
from matplotlib.animation import PillowWriter
from matplotlib.animation import FuncAnimation, FFMpegWriter
import matplotlib.animation as animation
import matplotlib as mpl
mpl.rcParams['animation.embed_limit'] = 120  # Erhöhe das Limit auf 50 MB
from numba import njit
import scipy.interpolate
from scipy.integrate import solve_ivp
from scipy.interpolate import SmoothBivariateSpline
from scipy.interpolate import RBFInterpolator

from google.colab import files #upload von unseren datensätzen
uploaded = files.upload()

# Hydrogen data
data_h_raw = pd.read_csv(
    "apjs504506t2_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_H_raw", "T_H_raw", "p_H_raw", "E_H_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_h_log = pd.DataFrame({
    "rho_H": np.log(data_h_raw["rho_H_raw"]),
    "T_H": np.log(data_h_raw["T_H_raw"]),
    "p_H": np.log(data_h_raw["p_H_raw"]),
    "E_H": np.log(data_h_raw["E_H_raw"])
}) #.dropna()

E_H_raw = data_h_raw["E_H_raw"]
p_H_raw = data_h_raw["p_H_raw"]
T_H_raw = data_h_raw["T_H_raw"]
rho_H_raw = data_h_raw["rho_H_raw"]
print(data_h_raw)

# Extract cleaned numpy arrays
rho_H = data_h_log["rho_H"].to_numpy()
T_H = data_h_log["T_H"].to_numpy()
p_H = data_h_log["p_H"].to_numpy()
E_H = data_h_log["E_H"].to_numpy()

Tp_H = np.column_stack((T_H, p_H))
rhoT = np.column_stack((T_H, rho_H))
rhoT_raw = np.column_stack((T_H_raw, rho_H_raw))

# Helium data
data_he_raw = pd.read_csv(
    "apjs504506t3_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_He_raw", "T_He_raw", "p_He_raw", "E_He_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_he_log = pd.DataFrame({
    "rho_He": np.log(data_he_raw["rho_He_raw"]),
    "T_He": np.log(data_he_raw["T_He_raw"]),
    "p_He": np.log(data_he_raw["p_He_raw"]),
    "E_He": np.log(data_he_raw["E_He_raw"])
}) #.dropna()

E_He_raw = data_he_raw["E_He_raw"]
p_He_raw = data_he_raw["p_He_raw"]
T_He_raw = data_he_raw["T_He_raw"]
rho_He_raw = data_he_raw["rho_He_raw"]

# Extract cleaned numpy arrays
rho_He = data_he_log["rho_He"].to_numpy()
T_He = data_he_log["T_He"].to_numpy()
p_He = data_he_log["p_He"].to_numpy()
E_He = data_he_log["E_He"].to_numpy()

Tp_He = np.column_stack((T_He, p_He))
rhoT_He = np.column_stack((T_He, rho_He))

# INTERPOLATOR

interpolatorHe = scipy.interpolate.LinearNDInterpolator(Tp_He, rho_He) #He

interpolatorENer = scipy.interpolate.LinearNDInterpolator(rhoT_raw, E_H_raw)
interpolatorENerHe = scipy.interpolate.LinearNDInterpolator(rhoT_He, E_He)

# für später unten im code für hydrogen: math.exp(interpolator([math.log(T[i]),math.log(p[i] / 1e9)])))

h = 1e-4
print(h)
print(interpolatorENer(300, 1000))

#ableitungen berechnen lassen

dE_dT_H = (
    interpolatorENer(T_H_raw + h, rho_H_raw)
    - interpolatorENer(T_H_raw, rho_H_raw)
) / (h)

dE_drho_H = (
    interpolatorENer(T_H, rho_H + h)
    - interpolatorENer(T_H, rho_H - h)
) / (2*h)

interpolator_dE_dT_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H, rho_H)),
    dE_dT_H
)
interpolator_dE_drho_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H, rho_H)),
    dE_drho_H
)

print(interpolatorENer(T_H + h, rho_H))
print(dE_dT_H)

dE_dT_He = (
    interpolatorENerHe(T_He + h, rho_He)
    - interpolatorENerHe(T_He - h, rho_He)
) / (2*h)
dE_drho_He = (
    interpolatorENerHe(T_He, rho_He + h)
    - interpolatorENerHe(T_He, rho_He - h)
) / (2*h)

interpolator_dE_dT_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He, rho_He)),
    dE_dT_He
)
interpolator_dE_drho_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He, rho_He)),
    dE_drho_He
)




drho_dT_H = (
    interpolator(T_H + h, p_H)
    - interpolator(T_H, p_H)
) / (h)
drho_dp_H = (
    interpolator(T_H, p_H + h)
    - interpolator(T_H, p_H - h)
) / (2*h)

interpolator_drho_dT_H = scipy.interpolate.LinearNDInterpolator(
    Tp_H,
    drho_dT_H
)
interpolator_drho_dp_H = scipy.interpolate.LinearNDInterpolator(
    Tp_H,
    drho_dp_H
)
print(drho_dT_H)



drho_dT_He = (
    interpolatorHe(T_He + h, p_He)
    - interpolatorHe(T_He - h, p_He)
) / (2*h)
drho_dp_He = (
    interpolatorHe(T_He, p_He + h)
    - interpolatorHe(T_He, p_He - h)
) / (2*h)

interpolator_drho_dT_He = scipy.interpolate.LinearNDInterpolator(
    Tp_He,
    drho_dT_He
)
interpolator_drho_dp_He = scipy.interpolate.LinearNDInterpolator(
    Tp_He,
    drho_dp_He
)

X = np.column_stack((T_H, p_H))
rbf = RBFInterpolator(X, rho_H,
                      kernel='thin_plate_spline')

Y = np.column_stack((T_H_raw, rho_H_raw, p_H_raw))
Ebf = RBFInterpolator(Y, E_H_raw,
                      kernel='thin_plate_spline')

XHe = np.column_stack((T_He, p_He))
rbfe = RBFInterpolator(XHe, rho_He,
                      kernel='thin_plate_spline')

YHe = np.column_stack((T_He_raw, rho_He_raw, p_He_raw))
Ebfe = RBFInterpolator(YHe, E_He_raw,
                      kernel='thin_plate_spline')

def drho_dp(T, p, h=1e-3):
    x1 = np.array([[T, p+h]])
    x2 = np.array([[T, p]])

    return ((rbf(x1) - rbf(x2)) / (h))

def drho_dT(T, p, h=1e-3):
    x1 = np.array([[T+h, p]])
    x2 = np.array([[T, p]])

    return (rbf(x1) - rbf(x2)) / (h)

def dE_drho(T, rho, p, h=1e-3):
    x1 = np.array([[T, rho + h, p]])
    x2 = np.array([[T, rho, p]])

    return (Ebf(x1) - Ebf(x2)) / (h)

def dE_dT(T, rho, p, h=1e-3):
    x1 = np.array([[T+h, rho, p]])
    x2 = np.array([[T, rho, p]])

    return (Ebf(x1) - Ebf(x2)) / (h)

#for T, rho, p in zip(T_H, rho_H, p_H):
 #   print(dE_dT(T, rho, p))

 #same for He:

def drho_dp_He(T, p, h=1e-3):
    x1 = np.array([[T, p+h]])
    x2 = np.array([[T, p]])

    return ((rbfe(x1) - rbfe(x2)) / (h))

def drho_dT_He(T, p, h=1e-3):
    x1 = np.array([[T+h, p]])
    x2 = np.array([[T, p]])

    return (rbfe(x1) - rbfe(x2)) / (h)

def dE_drho_He(T, rho, p, h=1e-3):
    x1 = np.array([[T, rho + h, p]])
    x2 = np.array([[T, rho, p]])

    return (Ebfe(x1) - Ebfe(x2)) / (h)

def dE_dT_He(T, rho, p, h=1e-3):
    x1 = np.array([[T+h, rho, p]])
    x2 = np.array([[T, rho, p]])

    return (Ebfe(x1) - Ebfe(x2)) / (h)

#interpolator_dE_dT_He(T_He, rho_He)    # ∂E/∂T
#interpolator_dE_drho_He(T_He, rho_He)  # ∂E/∂ρ

#Konstanten
METER=1.0
KG=1.0
SECOND=1.0
G = 6.674e-11*METER*METER*METER/KG/SECOND/SECOND

# aktuelles definieren von startbedingungen
rho_0 = 3000*KG/METER/METER/METER

"""Radius Funktion"""

def find_radius_profile(density, mass_profile):
  ''' INPUT:
      density = constant value or array of values
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT looks like
      r_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... ,[rN-1lower, rN-1, rN-1upper], [rNlower, rN, rNupper]]
      '''


  N = len(mass_profile)
  r_profile = np.zeros((N,3))
  if type(density) not in [np.ndarray, list]:
    density = np.full(N, density)

  rilower = 0

  deltar = []

  for i in range(1,N): #stops @ N-1 (index of shell N is N-1)
    ''' r1lowr == 0 und rilower == ri-1upper (rNupper == Radius_gesamt(?))
    START AT SHELL NUMBER 2 (index 1)
    STEP 1: Calculate rilower
    STEP 2: set ri-1upper == rilower
    STEP 3: calculate ri-1

    STEP 4: FORMULA (15) CHECK
    '''

    if i == 1:
      r_profile[1][0] = (3*mass_profile[i]/(4*np.pi*density[i]))**(1/3) #deltar1 FORMULA (21) #STEP 1
      r_profile[0][2] = r_profile[1][0] #STEP 2
      r_profile[0][1] = r_profile[0][2]/2 #STEP 3

      rilower += mass_profile[0]/(4*np.pi*density[0]*r_profile[0][1]**2) #FORMULA (22)

      deltar.append(mass_profile[0]/(4*np.pi*density[0]*r_profile[0][1]**2))


    if i != 1:
      r_profile[i-1][1] = r_profile[i-1][0] #for now? introducing an error of deltari/2

      rilower_first = rilower + mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) #FORMULA (22)

      r_profile[i][0] = rilower_first #STEP 1
      r_profile[i-1][2] = r_profile[i][0] #STEP 2
      r_profile[i-1][1] = (r_profile[i-1][0]+r_profile[i-1][2])/2 #STEP 3

      rilower += mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) #FORMULA (22)

      deltar.append(mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2))

    if i == N-1: #special treatment for last shell
      deltarN = mass_profile[i]/(4*np.pi*density[i]*r_profile[i][0]**2) # FORMULA (23)
      r_profile[i][2] = r_profile[i][0] + deltarN # FORMULA (24)
      r_profile[i][1] = (r_profile[i][0]+r_profile[i][2])/2

    ''' deltariminus1 = mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) # FORMULA (15)
      if r_profile[i-1][0] + deltariminus1 != r_profile[i-1][2]:
        print(f"FORMULA 15 difference for shell {i-1} is {r_profile[i-1][2]/(r_profile[i-1][0] + deltariminus1)}")
      elif r_profile[i-1][0] + deltariminus1 == r_profile[i-1][2]:
        print(f"FORMULA 15 works for shell {i-1}")'''

  return r_profile

"""Pressure Funktion"""

def find_pressure_profile(radius_profile, mass_profile):
  ''' INPUT:
      radius_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... , [rNlower, rN, rNupper]]
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT should look like
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]'''

  N = len(radius_profile)
  if len(mass_profile) != N:
    raise ValueError("mass_profile and radius_profile must have the same length")

  p_profile = np.zeros((N,3))

  p_profile[-1][2] = 100000

  for i in range(N-1,0,-1): #starts @ N-1 (index of shell N) and goes down to 1 (index of shell 2)
    p_profile[i-1][2] = np.sum(G/(4*np.pi)*np.array([mass_profile[j]*np.sum([mass_profile[k] for k in range(j)]) / radius_profile[j][1]**4 for j in range(N-1, i-1,-1)])) #FORMULA (17)
    p_profile[i][0] = p_profile[i-1][2]

    p_profile[i][1] = (p_profile[i][0]+p_profile[i][2])/2 #FORMULA (16)

  #afterwards special treatment for i=0 (shell 1) [0, 0, r1upper]
  p_profile[0][0] = p_profile[0][2] + 3*G*mass_profile[0]**2/(8*np.pi*radius_profile[0][2]**4) #deltar1 FORMULA (19)
  p_profile[0][1] = (p_profile[0][0]+p_profile[0][2])/2

  return p_profile

# BEISPIEL Asteroid
density = 3000 #kg/m^3
radius_gesamt = 250 #m
gesamtmasse = 4/3 * np.pi * radius_gesamt**3 * density #kg
N=10
mass_profile_as = [gesamtmasse/N for i in range(N)]
r_profile_as = find_radius_profile(density, mass_profile_as)
print(r_profile_as)

p_profile_as = find_pressure_profile(r_profile_as, mass_profile_as)
print(p_profile_as)
T = np.full(N, 165)
rho=[]
for i in range(N):
  rho.append(math.exp(interpolator([math.log(T[i]),math.log(p_profile_as[i][1] / 1e9)])[0])*1000)

print(rho)

#Anfangsbedingungen:
N = 10
T = np.full(N, 165)     # K
mass_total = 1.898e27   # kg
mass_profile = np.full(N, mass_total / N)

#Startbedingung
density_0 = 1326        #kg/m^3
rho = np.full(N, density_0)

# Konvergenzparameter
tolerance = 1e-6
max_iter = 20

for iteration in range(max_iter):

    r_profile = find_radius_profile(rho, mass_profile)
    p_profile = find_pressure_profile(r_profile, mass_profile)

# Neue Dichten aus EOS berechnen
    rho_new = []

    for i in range(N):

        # Druck in GPa für Interpolator
        p_gpa = p_profile[i][1] / 1e9

        rho_i = math.exp(interpolator([math.log(T[i]),math.log(p_gpa)])[0]) * 1000
        rho_new.append(rho_i)

    rho_new = np.array(rho_new)

    # relative Änderung der zentralen Dichte
    rel_diff = abs(rho_new[0] - rho[0]) / rho[0]

    print(f"Relative Änderung bei Iteration {iteration+1}:", rel_diff)

    # Abbruchbedingung
    if rel_diff < tolerance:
        print("\nKonvergenz erreicht.")
        break

    # neues Profil übernehmen
    rho = rho_new.copy()


print("\nFinales Radiusprofil:")
print(r_profile)

print("\nFinales Druckprofil:")
print(p_profile)

print("\nFinales Dichteprofil:")
print(rho_new)

# BEISPIEL Jupiter

density = 1326 #kg/m^3

N=100
mass_gesamt = 1.898e27 #kg

mass_profile_j = [mass_gesamt/N for _ in range(N)]

r_profile_j = find_radius_profile(density, mass_profile_j)

#print(r_profile_j)

p_profile_j = find_pressure_profile(r_profile_j, mass_profile_j)
print(p_profile_j)
T = np.full(N, 165)
rho=[]
for i in range(N):
  rho.append(math.exp(interpolator([math.log(T[i]),math.log(p_profile_j[i][1] / 1e9)])[0])*1000)

print(rho)

def rocky_eos(pressure_profile, K_0, K_d, rho_0):
  N = len(pressure_profile)
  density_profile = np.zeros(N)

  for i in range(N):
    density_profile[i] = rho_0*(1+K_d*pressure_profile[i][1]/K_0)**(1/K_d)

  return density_profile

def h_eos(pressure_profile, T):
  N = len(pressure_profile)
  if len(T) != N:
    raise ValueError("T and pressure_profile must have the same length")

  density_profile = np.zeros(N) #was before 'np.zeros((N,3))', but this does not make sense right?

  for i in range(N):
    density_profile[i] = math.exp(interpolator([math.log(T[i]),math.log(pressure_profile[i][1] / 1e9)])[0])*1000

  return density_profile

def he_eos(pressure_profile, T):
  N = len(pressure_profile)
  if len(T) != N:
    raise ValueError("T and pressure_profile must have the same length")

  density_profile = np.zeros(N) #was before 'np.zeros((N,3))', but this does not make sense right?

  for i in range(N):
    density_profile[i] = math.exp(interpolatorHe([math.log(T[i]),math.log(pressure_profile[i][1] / 1e9)])[0]) * 1000

  return density_profile

def density_from_eos(pressure_profile, temperature, eos='h', **kwargs):
  ''' INPUT:
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]
      temperature = [T1, T2, ..., Tn]
      eos = which equation of state to use? "he", "h", "rocky"(then K_0 and K'_0 and rho_0 need to be provided)

      FUNCTION gives the density from an equation of state. Different Equation of states

      OUTOUT should look like
      density = [[rho1lower, rho1, rho1upper], [rho2lower, rho2, rho2upper], ..., [rhoNlower, rhoN, rhoNupper]]
      '''
  if type(temperature) not in [np.ndarray, list]:
    temperature = np.full(len(pressure_profile), temperature)
  T = np.array(temperature)

  if eos == "he":
    density_profile = he_eos(pressure_profile, T)
  elif eos == "h":
    density_profile = h_eos(pressure_profile, T)
  elif eos == "rocky":
    if "k_0" not in kwargs or "k_d" not in kwargs or "rho_0" not in kwargs:
      raise ValueError("'k_0', 'k_d'(k_0') and 'rho_0' must be provided for the rocky equation of state")

    K_0 = kwargs['k_0']
    K_d = kwargs['k_d']
    rho_0 = kwargs['rho_0']
    density_profile = rocky_eos(pressure_profile, K_0, K_d, rho_0)
  else:
    raise ValueError(f"Unknown equation of state: {eos}")

  return density_profile


def one_cycle(mass_profile, first_density, temperature, **kwargs):
  ''' INPUT:
      mass_profile = [m1,m2,m3,..., mN]
      first_density = constant value or array of values

      FUNCTION represents one cycle

      OUTPUT should look like
      new_density = [[rho1lower, rho1, rho1upper], [rho2lower, rho2, rho2upper], ..., [rhoNlower, rhoN, rhoNupper]]
      '''

  r_profile = find_radius_profile(first_density, mass_profile) #RADIUS
  p_profile = find_pressure_profile(r_profile, mass_profile) #PRESSURE

  new_density = density_from_eos(p_profile, temperature, **kwargs) #EQUATION OF STATE

  return r_profile, p_profile, new_density

"""**multiple cycles function**"""

def create_mass_profile(mass_total, N, profile='constant'):
  if profile == 'constant':
    mass_profile = np.full(N, mass_total / N)
  elif profile == 'linear':
    mass_profile = np.linspace(mass_total / N, mass_total, N)
  # add more mass distribution profiles?
  return mass_profile

def create_temp_profile(T, N, profile='constant'):
  if profile == 'constant':
    T_profile = np.full(N, T)
  elif profile == 'linear':
    T_profile = np.linspace(T, 0, N) #this does not make sense right?
  return T_profile

def create_density_profile(rho, N, profile='constant'):
  if profile == 'constant':
    density_profile = np.full(N, rho)
  elif profile == 'linear':
    density_profile = np.linspace(rho, 0, N)
  return density_profile

################################################################################

def multi_iteration(starting_density, mass_total, N, T, mass_profile=None,
                    mass_distro_profile='constant', temp_distro_profile='constant',
                    density_distro_profile='constant', tolerance=1e-6, max_iter=20,
                    quiet=True, **kwargs):
  if mass_profile==None:
    mass_profile = create_mass_profile(mass_total, N, profile=mass_distro_profile)
  else:
    mass_profile = np.array(mass_profile)

  if type(T) in [np.ndarray, list]:
    T = T
  else:
    T = create_temp_profile(T, N, profile=temp_distro_profile)

  if type(starting_density) in [np.ndarray, list]:
    rho = starting_density
  else:
    rho = create_density_profile(starting_density, N, profile=density_distro_profile)

  for iteration in range(max_iter):
    r_profile, p_profile, new_rho = one_cycle(mass_profile, rho, T, **kwargs)

    rel_diff = abs(new_rho[0] - rho[0]) / rho[0]

    if quiet == False:
      print(f"Relative Änderung bei Iteration {iteration+1}:", rel_diff)

    # Abbruchbedingung
    if rel_diff < tolerance:
      if quiet == False:
        print("\nKonvergenz erreicht.")
      break

    # neues Profil übernehmen
    rho = new_rho.copy()

  if quiet == False:
    print("\nFinales Radiusprofil:")
    print(r_profile)

    print("\nFinales Druckprofil:")
    print(p_profile)

    print("\nFinales Dichteprofil:")
    print(new_rho)

  return r_profile, p_profile, new_rho

"""## adiabatic temperature"""

T_0 = ... #surfacetemp
p_0 = p_profile[-1][2] #surfacepreassure
gamma_He = 1.60 #helium? sources...
gamma_H2 = 1.40

T = T_0 * (p_profile[i][1] / p_0)**((gamma - 1)/gamma) #allgemeine formel

"""einbauen von verschiedenen gammas durch den übergang zu verschiedenen elementen:"""

T0 = 300

# Liste für Temperaturen
temperatures = [T0]

gamma_layers = [
    (2, 1.4),   # bis i=2 -> gamma=1.4
    (4, 1.66)   # ab i=3 bis i=4 -> gamma=1.66
]

current_layer = 0
gamma = gamma_layers[current_layer][1]

for i in range(1, len(p_profile)):

    # r_upper des aktuellen Eintrags
    r_upper = r_profile[i][2]

    # Gamma abhängig vom Radius
    if r_upper >= 10:
        gamma = 1.4
    else:
        gamma = 1.66

    # Prüfen ob Layerwechsel
    if i > gamma_layers[current_layer][0]:
        current_layer += 1
        gamma = gamma_layers[current_layer][1]

    T_prev = temperatures[-1]
    p_prev = p_profile[i-1][1]

    p_new = p_profile[i][1]

    # Neue Temperatur
    T_new = T_prev * (p_new / p_prev)**((gamma - 1)/gamma)

    temperatures.append(T_new)

print(temperatures)

T0 = 300 # surface temp.
gamma_layers = [
    (10, 1.4),
    (-float("inf"), 1.66) #wenn r <10 -> gamma profile
]
temperatures = [T0]

for i in range(1, len(p_profile)):

    r_upper = r_profile[i][2]

    # passendes gamma bestimmen
    for r_limit, gamma_value in gamma_layers:
        if r_upper >= r_limit:
            gamma = gamma_value
            break

    T_prev = temperatures[-1]

    p_prev = p_profile[i - 1][1]
    p_new  = p_profile[i][1]

    T_new = T_prev * (p_new / p_prev) ** ((gamma - 1) / gamma) #adiabatische poissonschen Gesetze

    temperatures.append(T_new)

print(temperatures)

1# adiabta. T nach Entropie

#dTnachdp = - drhonachdP / (drhonachdT + unachT * (unachrho - p_rofile / rho)**(-1))

dTdp_H = - interpolator_drho_dp_H(T_H, p_H) / (interpolator_drho_dT_H(T_H, p_H) + interpolator_dE_dT_H(T_H, rho_H) * (interpolator_dE_drho_H(T_H, rho_H) - p_H / rho_H)**(-1))
dTdp_He = - interpolator_drho_dp_He(T_He, p_He) / (interpolator_drho_dT_He(T_He, p_He) + interpolator_dE_dT_He(T_He, rho_He) * (interpolator_dE_drho_He(T_He, rho_He) - p_He / rho_He)**(-1))

#T profile für jupiter, wasserstoff
T_0 = 300 #[K] surfacetemp
p_profile = p_profile_j[:, 2]#nur kurz hier für jupiter + nur aus 3. spalte die werte berechnen

rho = np.array(rho)


T_profile = np.zeros_like(p_profile)
#T_profile[-1] = T_0
T_profile[0] = T_0

#dE_dT_list = []

#for i in range(len(p_profile)-1, -1, -1):
for i in range(len(p_profile)-1):
    print(T_profile[i])
    p = math.log(p_profile[i]/1e9) # in GPa
    T = math.log(T_profile[i])
    rho_val = math.log(rho[i])


    #rho = interpolatorHe(T, p) im normalfall hier berechnen - wurde schon getan für jupiter bzw. wird an anderer stelle getan
    dE_dT_val = math.exp(dE_dT(T, rho_val, p)[0])
    #dE_dT_list.append(dE_dT_val)
    dE_drho_val = math.exp(dE_drho(T, rho_val, p)[0])
    drho_dp_val = math.exp(drho_dp(T, p)[0])
    drho_dT_val = math.exp(drho_dT(T, p)[0])

    #drho_dp = math.exp(interpolator_drho_dp_H(T, p)) #nan

    #drho_dT = math.exp(interpolator_drho_dT_H(T, p)) #nan

    #dE_dT = math.exp(interpolator_dE_dT_H(T, rho_val)) #nan
    #dE_drho = math.exp(interpolator_dE_drho_H(T, rho_val)) #nan

    dTdp = drho_dp_val / (
        drho_dT_val
        + dE_dT_val * (dE_drho_val - math.exp(p)/math.exp(rho_val)**2)**(-1)
    )

    dp = p_profile[i+1]/1e9 - p_profile[i]/1e9 #math.exp(p)

    T_profile[i+1] = T + dTdp * dp

T_0 = 300
p_profile = p_profile_j[:, 2]
T_profile = np.zeros_like(p_profile)
# Randbedingung am Ende
T_profile[-1] = T_0

for i in range(len(p_profile)-1, 0, -1):

    print(T_profile[i])
    print(f'dichte:{rho[i]}')

    p = math.log(p_profile[i] / 1e9)
    T = math.log(T_profile[i])
    rho_val = math.log(rho[i])
    p2 = p_profile[i] / 1e9
    T2 = T_profile[i]
    rho_val2 = rho[i]

    dE_dT_val = dE_dT(T2, rho_val2, p2)[0]
    dE_drho_val = dE_drho(T2, rho_val2, p2)[0]
    drho_dp_val = math.exp(drho_dp(T, p)[0])
    drho_dT_val = math.exp(drho_dT(T, p)[0])

    dTdp = drho_dp_val / (
        drho_dT_val
        + dE_dT_val * (dE_drho_val - p2/rho_val2**2)**(-1)
    )

    #same for He:
    dE_dT_vale = dE_dT_He(T2, rho_val2, p2)[0]
    dE_drho_vale = dE_drho_He(T2, rho_val2, p2)[0]
    drho_dp_vale = math.exp(drho_dp_He(T, p)[0])
    drho_dT_vale = math.exp(drho_dT_He(T, p)[0])

    dTdpHe = - drho_dp_vale / (
        drho_dT_vale
        + dE_dT_vale * (dE_drho_vale - p2/math.exp(rho_val)**2)**(-1)
    )

    dp = p_profile[i-1]/1e9 - p_profile[i]/1e9

    T_profile[i-1] = math.exp(T) + dTdp * dp

print(p_profile)

T_0 = 300 #[K] surfacetemp
p_profile = p_profile_j[:, 2]#nur kurz hier für jupiter + nur aus 3. spalte die werte berechnen
rho = np.array(rho)

T_profile = np.zeros_like(p_profile)
T_profile[0] = T_0

for i in range(len(p_profile)-1):

    p = math.log(p_profile[i])
    T = math.log(T_profile[i])
    rho_val = math.log(rho[i])

    #rho = interpolatorHe(T, p) im normalfall hier berechnen - wurde schon getan für jupiter bzw. wird an anderer stelle getan

    drho_dp = np.exp(interpolator_drho_dp_H([T, p])[0])
    drho_dT = np.exp(interpolator_drho_dT_H([T, p])[0])

    dE_dT = np.exp(interpolator_dE_dT_H([T, rho_val])[0])
    dE_drho = np.exp(interpolator_dE_drho_H([T, rho_val])[0])

    dTdp = - drho_dp / (
        drho_dT
        + dE_dT * (dE_drho - p/rho_val**2)**(-1)
    )

    dp = p_profile[i+1] - p

    T_profile[i+1] = T + dTdp * dp

print(T_profile)
print(dTdp)
print(drho_dT)

"""# **TESTS**"""

# Jupiter recreation

R, P, rho = multi_iteration(1326, 1.898e27, 100, 165, quiet=False, eos='h')

print(np.mean(rho))

"""## **rocky eos parameters**

Iron (Wagner+2011):
* rho_0 = 8269.4 kg/m^3
* K_0 = 149.4 GPa
* K_0' = 5.650

Ice (Wagner+2011):
* rho_0 = 1249.5 kg/m^3
* K_0 = 4.26 GPa
* K_0' = 7.75

Hydrated Silicate Mixture (ChatGPT):
* rho = 2200-2800
* K_0 = 20-70
* K_0' = 4-7

Pyrolite (Solomatova+2021 https://pmc.ncbi.nlm.nih.gov/articles/PMC7900987/) at 2000K:
* rho = 2490
* K_0 = 24
* K_0' = 4.7

Olivine (Wagner+2011):
* rho = 3213.7
* K_0 = 127.4
* K_0' = 4.2

"""

# Ceres
'''mass = 9.38392e20 kg
mean density = 2161.6 kg/m^3
mean surface temp = 172.5 K
mean radius = 469.7 km

C-type / G-type
Composition: hydrated silicates - core
             porous icy crust   - outer shell'''

# icy variant , k_0=4.26e9, k_d=7.75, rho_0=1249.5)
# hydrated silicate mixture , k_0=70e9, k_d=7, rho_0=2800)
# pyrolite , k_0=24e9, k_d=4.7, rho_0=2490)
#olivine , k_0=127.4e9, k_d=4.2, rho_0=3213.7)

R, P, rho = multi_iteration(2161.6, 9.38392e20, 10, 172.5, quiet=False, eos='rocky', k_0=70e9, k_d=7, rho_0=2800)

print('Mean Density: ', np.mean(rho))



"""# to do <br>

- adiabatischers temperaturprofil funktion
- adiabat. T entropie beschreiben
- verschiedene materialien für verschiedene schichten - zustandsfunktion
-  verschiedene materialien für verschiedene schichten - bei adiabat T
- wie materialabhängigkeit für T und Eos zusammenfassen
- ceres zentrumdruck nachrrechnen
- optimieren material(verteilung) mit funktion automatisieren
"""

