# -*- coding: utf-8 -*-
"""lab_ordenlicher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OGqUA7bwywvo_1xOPRg9ZRdTnKiUzrCa
"""

import numpy as np
import matplotlib.pyplot as plt
import math
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
from math import pi
from numpy import radians, degrees, sin, cos, arccos, sqrt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML
from matplotlib.colors import Normalize
from matplotlib.animation import PillowWriter
from matplotlib.animation import FuncAnimation, FFMpegWriter
import matplotlib.animation as animation
import matplotlib as mpl
mpl.rcParams['animation.embed_limit'] = 120  # Erhöhe das Limit auf 50 MB
from numba import njit
import scipy.interpolate
from scipy.integrate import solve_ivp
from scipy.interpolate import SmoothBivariateSpline
from scipy.interpolate import RBFInterpolator

from google.colab import files #upload von unseren datensätzen
uploaded = files.upload()

# Hydrogen data
data_h_raw = pd.read_csv(
    "apjs504506t2_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_H_raw", "T_H_raw", "p_H_raw", "E_H_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_h_log = pd.DataFrame({
    "rho_H": np.log(data_h_raw["rho_H_raw"] * 1000), #[kg/m^3]
    "T_H": np.log(data_h_raw["T_H_raw"]),
    "p_H": np.log(data_h_raw["p_H_raw"] * 1e9), #[Pa]
    "E_H": np.log(data_h_raw["E_H_raw"] * 1e6)
}) #.dropna()

E_H_raw = data_h_raw["E_H_raw"] * 1e6
p_H_raw = data_h_raw["p_H_raw"] * 1e9
T_H_raw = data_h_raw["T_H_raw"]
rho_H_raw = data_h_raw["rho_H_raw"] * 1000
#print(data_h_raw)

# Extract cleaned numpy arrays
rho_H = data_h_log["rho_H"].to_numpy()
T_H = data_h_log["T_H"].to_numpy()
p_H = data_h_log["p_H"].to_numpy()
E_H = data_h_log["E_H"].to_numpy()

Tp_H = np.column_stack((T_H, p_H))
rhoT = np.column_stack((T_H, rho_H))
rhoT_raw = np.column_stack((T_H_raw, rho_H_raw))
Tp_H_raw = np.column_stack((T_H_raw, p_H_raw))

# Helium data
data_he_raw = pd.read_csv(
    "apjs504506t3_mrt.txt",
    sep=r"\s+",
    skiprows=15,
    usecols=[0, 1, 2, 3],
    names=["rho_He_raw", "T_He_raw", "p_He_raw", "E_He_raw"]
)

# Apply log transformation to all columns and then drop rows with any NaN values
data_he_log = pd.DataFrame({
    "rho_He": np.log(data_he_raw["rho_He_raw"] * 1000),
    "T_He": np.log(data_he_raw["T_He_raw"]),
    "p_He": np.log(data_he_raw["p_He_raw"] * 1e9),
    "E_He": np.log(data_he_raw["E_He_raw"] * 1e6)
}) #.dropna()

E_He_raw = data_he_raw["E_He_raw"] * 1e6
p_He_raw = data_he_raw["p_He_raw"] * 1e9
T_He_raw = data_he_raw["T_He_raw"]
rho_He_raw = data_he_raw["rho_He_raw"] * 1000

# Extract cleaned numpy arrays
rho_He = data_he_log["rho_He"].to_numpy()
T_He = data_he_log["T_He"].to_numpy()
p_He = data_he_log["p_He"].to_numpy()
E_He = data_he_log["E_He"].to_numpy()

Tp_He = np.column_stack((T_He, p_He))
rhoT_He = np.column_stack((T_He, rho_He))
Tp_He_raw = np.column_stack((T_He_raw, p_He_raw))
rhoT_He_raw = np.column_stack((T_He_raw, rho_He_raw))

interpolator = scipy.interpolate.LinearNDInterpolator(Tp_H, rho_H) # Hydrogen
interpolatorHe = scipy.interpolate.LinearNDInterpolator(Tp_He, rho_He) #He

interpolatorENer = scipy.interpolate.LinearNDInterpolator(rhoT_raw, E_H_raw)
interpolatorENerHe = scipy.interpolate.LinearNDInterpolator(rhoT_He_raw, E_He_raw)

#paramerter:
G = 6.674e-11
h = 1e-4

dE_dT_H = (
    interpolatorENer(T_H_raw + h, rho_H_raw)
    - interpolatorENer(T_H_raw, rho_H_raw)
) / (h)

dE_drho_H = (
    interpolatorENer(T_H_raw, rho_H_raw + h)
    - interpolatorENer(T_H_raw, rho_H_raw - h)
) / (h)

interpolator_dE_dT_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H_raw, rho_H_raw)),
    dE_dT_H
)
interpolator_dE_drho_H = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_H_raw, rho_H_raw)),
    dE_drho_H
)


dE_dT_He = (
    interpolatorENerHe(T_He_raw + h, rho_He_raw)
    - interpolatorENerHe(T_He_raw, rho_He_raw)
) / (h)
dE_drho_He = (
    interpolatorENerHe(T_He_raw, rho_He_raw + h)
    - interpolatorENerHe(T_He_raw, rho_He_raw)
) / (h)

interpolator_dE_dT_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He_raw, rho_He_raw)),
    dE_dT_He
)
interpolator_dE_drho_He = scipy.interpolate.LinearNDInterpolator(
    np.column_stack((T_He_raw, rho_He_raw)),
    dE_drho_He
)

def drho_dT_H3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogT = (
        interpolator(logT + h, logp)
        - interpolator(logT, logp)
    ) / h

    return (rhoo / T_) * dlogrho_dlogT

def drho_dT_He3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogT = (
        interpolatorHe(logT + h, logp)
        - interpolatorHe(logT, logp)
    ) / h

    return (rhoo / T_) * dlogrho_dlogT

def drho_dp_H3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogp = (
        interpolator(logT, logp + h)
        - interpolator(logT, logp)
    ) / h

    return (rhoo / p_) * dlogrho_dlogp

def drho_dp_He3(T_, p_, rhoo):
    logT = np.log(T_)
    logp = np.log(p_)

    dlogrho_dlogp = (
        interpolatorHe(logT, logp + h)
        - interpolatorHe(logT, logp)
    ) / h

    return (rhoo / p_) * dlogrho_dlogp

"""# Radiusfunktion"""

def find_radius_profile(density, mass_profile):
  ''' INPUT:
      density = constant value or array of values
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT looks like
      r_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... ,[rN-1lower, rN-1, rN-1upper], [rNlower, rN, rNupper]]
      '''


  N = len(mass_profile)
  r_profile = np.zeros((N,3))
  if type(density) not in [np.ndarray, list]:
    density = np.full(N, density)

  rilower = 0

  deltar = []

  for i in range(1,N): #stops @ N-1 (index of shell N is N-1)
    ''' r1lowr == 0 und rilower == ri-1upper (rNupper == Radius_gesamt(?))
    START AT SHELL NUMBER 2 (index 1)
    STEP 1: Calculate rilower
    STEP 2: set ri-1upper == rilower
    STEP 3: calculate ri-1

    STEP 4: FORMULA (15) CHECK
    '''

    if i == 1:
      r_profile[1][0] = (3*mass_profile[i]/(4*np.pi*density[i]))**(1/3) #deltar1 FORMULA (21) #STEP 1
      r_profile[0][2] = r_profile[1][0] #STEP 2
      r_profile[0][1] = r_profile[0][2]/2 #STEP 3

      rilower += mass_profile[0]/(4*np.pi*density[0]*r_profile[0][1]**2) #FORMULA (22)

      deltar.append(mass_profile[0]/(4*np.pi*density[0]*r_profile[0][1]**2))


    if i != 1:
      r_profile[i-1][1] = r_profile[i-1][0] #for now? introducing an error of deltari/2

      rilower_first = rilower + mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) #FORMULA (22)

      r_profile[i][0] = rilower_first #STEP 1
      r_profile[i-1][2] = r_profile[i][0] #STEP 2
      r_profile[i-1][1] = (r_profile[i-1][0]+r_profile[i-1][2])/2 #STEP 3

      rilower += mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) #FORMULA (22)

      deltar.append(mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2))

    if i == N-1: #special treatment for last shell
      deltarN = mass_profile[i]/(4*np.pi*density[i]*r_profile[i][0]**2) # FORMULA (23)
      r_profile[i][2] = r_profile[i][0] + deltarN # FORMULA (24)
      r_profile[i][1] = (r_profile[i][0]+r_profile[i][2])/2

    ''' deltariminus1 = mass_profile[i-1]/(4*np.pi*density[i-1]*r_profile[i-1][1]**2) # FORMULA (15)
      if r_profile[i-1][0] + deltariminus1 != r_profile[i-1][2]:
        print(f"FORMULA 15 difference for shell {i-1} is {r_profile[i-1][2]/(r_profile[i-1][0] + deltariminus1)}")
      elif r_profile[i-1][0] + deltariminus1 == r_profile[i-1][2]:
        print(f"FORMULA 15 works for shell {i-1}")'''

  return r_profile

"""# Pressure function"""

def find_pressure_profile(radius_profile, mass_profile):
  ''' INPUT:
      radius_profile = [[r1lower, r1, r1upper], [r2lower, r2, r2upper], [r3lower, r3, r3upper], ... , [rNlower, rN, rNupper]]
      mass_profile = [m1,m2,m3,..., mN]

      OUTPUT should look like
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]'''

  N = len(radius_profile)
  if len(mass_profile) != N:
    raise ValueError("mass_profile and radius_profile must have the same length")

  p_profile = np.zeros((N,3))

  p_profile[-1][2] = 100000

  for i in range(N-1,0,-1): #starts @ N-1 (index of shell N) and goes down to 1 (index of shell 2)
    p_profile[i-1][2] = np.sum(G/(4*np.pi)*np.array([mass_profile[j]*np.sum([mass_profile[k] for k in range(j)]) / radius_profile[j][1]**4 for j in range(N-1, i-1,-1)])) #FORMULA (17)
    p_profile[i][0] = p_profile[i-1][2]

    p_profile[i][1] = (p_profile[i][0]+p_profile[i][2])/2 #FORMULA (16)

  #afterwards special treatment for i=0 (shell 1) [0, 0, r1upper]
  p_profile[0][0] = p_profile[0][2] + 3*G*mass_profile[0]**2/(8*np.pi*radius_profile[0][2]**4) #deltar1 FORMULA (19)
  p_profile[0][1] = (p_profile[0][0]+p_profile[0][2])/2

  return p_profile

"""# Temperatur function"""

def find_T_profile(pressure_profile, eos_profile, density_profile, T_0):
  p_profile = pressure_profile[:, 2]

  T_profile = np.zeros_like(p_profile)
  T_profile[-1] = T_0

  for i in range(len(p_profile)-1, 0, -1):

      T = T_profile[i]
      p = p_profile[i]
      rho_val = density_profile[i]

      dE_dT_val = interpolator_dE_dT_H(np.column_stack((T, rho_val)))[0]
      dE_drho_val = interpolator_dE_drho_H(np.column_stack((T, rho_val)))[0]
      drho_dT_val = drho_dT_H3(T, p, rho_val)
      drho_dp_val = drho_dp_H3(T, p, rho_val)

      dTdpH = drho_dp_val / (drho_dT_val + dE_dT_val * (dE_drho_val - p/rho_val**2)**(-1))

    # Helium
      dE_dT_vale = interpolator_dE_dT_He(np.column_stack((T, rho_val)))[0]
      dE_drho_vale = interpolator_dE_drho_He(np.column_stack((T, rho_val)))[0]
      drho_dT_vale = drho_dT_He3(T, p, rho_val)
      drho_dp_vale = drho_dp_He3(T, p, rho_val)

      dTdpHe = drho_dp_vale / (drho_dT_vale + dE_dT_vale * (dE_drho_vale - p/rho_val**2)**(-1))

    # Materialwahl

      dTdp = dTdpHe if eos_profile[i]['eos'] != 'h' else dTdpH

      dp = (p_profile[i-1] - p_profile[i])

      deltaT = dTdp * dp

      T_profile[i-1] = T + max(deltaT, 0)

  return T_profile

"""# density profile iterativ"""

import numpy as np

def create_eos_profile(layers_def):
    '''INPUT Example:

    layer_definitions_example = [
    {
        'eos_type': 'rocky',
        'params': {'k_0': 200e9, 'k_d': 3.5, 'rho_0': 5500},
        'num_layers': 50 # 50 layers for the rocky core
    },
    {
        'eos_type': 'h',
        'params': {'temperature': 100000}, # Assuming a constant temperature for this hydrogen section
        'num_layers': 50 # 50 layers for the hydrogen shell
    }
]

    OUTPUT should be a list of dictionaries.
  '''
    full_eos_profile=[]

    for layer_dict in layers_def:
        eos_type = layer_dict['eos_type']
        if 'params' in layer_dict:
            params_dict = layer_dict['params']
        n_layers = layer_dict['num_layers']
        for _ in range(n_layers):
            layer={'eos': eos_type}
            layer.update(params_dict)
            full_eos_profile.append(layer)

    return full_eos_profile

def rocky_eos(pressure, K_0, K_d, rho_0):
    if hasattr(pressure, "ndim") and pressure.ndim > 1:
        P = pressure[:, 1]
    else:
        P = pressure
    return rho_0*(1+K_d*P/K_0)**(1/K_d)

def calc_density_eos(pressure, T, interp = interpolator, log_x_interp=True):
    """Berechnet das Dichteprofil mithilfe einer Zustandsgleichung (EOS) gegeben durch den Interpolator.

    Die Funktion wertet einen Interpolator basierend auf der Temperatur und dem
    Druck aus. Sie ist flexibel und akzeptiert sowohl einzelne Skalarwerte als
    auch Arrays. Falls ein 2D-Druckprofil übergeben wird, extrahiert sie
    automatisch die relevante Druckspalte.

    Parameters
    ----------
    pressure : float, array_like of shape (N,) or (N, 3)
        Das Druckprofil. Kann eine einzelne Zahl (Skalar), ein 1D-Array
        oder ein 2D-Array mit 3 Spalten sein (hierbei wird die 2. Spalte mit Index 1 genutzt).
        Einheit der Eingabe: Pascal (Pa).
    T : float or array_like of shape (N,)
        Das Temperaturprofil in Kelvin (K). Muss dieselbe Länge wie
        `pressure` haben, wenn Arrays übergeben werden.
    interp : callable
        Die Interpolationsfunktion (z. B. für Wasserstoff oder Helium).
        Erwartet eine Liste/ein Array mit ``[T, P]`` und
        gibt ein Array zurück, dessen erstes Element [0] den Dichtewert enthält.

    Returns
    -------
    density_profile : float or ndarray of shape (N,)
        Die berechnete Dichte in kg/m³. Gibt einen einzelnen Skalar zurück,
        wenn die Eingaben Skalare waren, andernfalls ein Array.

    Raises
    ------
    ValueError
        Wenn `T` und `pressure_profile` als Arrays übergeben werden,
        aber nicht die gleiche Länge haben.
    """
    is_iterable = hasattr(pressure, "__len__") or hasattr(T, "__len__")

    if is_iterable:
        P = np.asarray(pressure)
        T = np.asarray(T)

        N = len(pressure)
        if len(T) != N:
            raise ValueError("T and pressure_profile must have the same length")

        P = P[:,1] if P.ndim > 1 else P

        if log_x_interp:
            density_profile = np.exp(interp([np.log(T), np.log(P)]))[0]
        else:
            density_profile = np.exp(interp([T, P]))[0]

        return density_profile
    else:
        P = np.asarray(pressure)
        P = P[:,1] if P.ndim > 1 else P
        T = np.asarray(T)
        if log_x_interp:
            density_profile = np.exp(interp([np.log(T), np.log(P)]))[0]
        else:
            density_profile = np.exp(interp([T, P]))[0]

        return density_profile

def density_from_eos_profile(pressure_profile, temperature, eos_profile, interpH=interpolator, interpHe=interpolatorHe, **kwargs):
  ''' INPUT:
      pressure_profile = [[p1lower, p1, p1upper], [p2lower. p2, p2upper], ..., [pNlower, pN, pNupper]]
      temperature = [T1, T2, ..., Tn]
      eos = which equation of state to use? "he", "h", "rocky"(then K_0 and K'_0 and rho_0 need to be provided)

      FUNCTION gives the density from an equation of state. Different Equation of states

      OUTOUT should look like
      density = [[rho1lower, rho1, rho1upper], [rho2lower, rho2, rho2upper], ..., [rhoNlower, rhoN, rhoNupper]]
      '''
  N = len(pressure_profile)
  if N != len(eos_profile):
      raise ValueError('eos_profile needs to be same lenght as pressure_profile')

  if type(temperature) not in [np.ndarray, list]:
    temperature = np.full(N, temperature)
  T = np.array(temperature)

  density_profile = np.zeros(N)

  for i, layer_dict in enumerate(eos_profile):
      eos=layer_dict['eos']

      if eos == "he":
          density_profile[i] = calc_density_eos(pressure_profile[i][1], T[i], interp=interpH)
      elif eos == "h":
          density_profile[i] = calc_density_eos(pressure_profile[i][1], T[i], interp=interpHe)
      elif eos == "rocky":
          if "k_0" not in layer_dict or "k_d" not in layer_dict or "rho_0" not in layer_dict:
              raise ValueError(f"'k_0', 'k_d'(k_0') and 'rho_0' must be provided for the rocky equation of state in shell with index {i}")

          K_0 = layer_dict['k_0']
          K_d = layer_dict['k_d']
          rho_0 = layer_dict['rho_0']
          density_profile[i] = rocky_eos(pressure_profile[i][1], K_0, K_d, rho_0)
      else:
          raise ValueError(f"Unknown equation of state: {eos} in shell with index {i}!")

  return density_profile

def one_cycle_var(mass_profile, first_density, temperature, eos_profile, **kwargs):
  ''' INPUT:
      mass_profile = [m1,m2,m3,..., mN]
      first_density = constant value or array of values
      temperature = [T1, T2, ..., Tn]
      eos_profile = {first transition: 'eos_below_first_transition',
                     second transition: 'eos_between_first_and_second_transition',
                     ...}
      FUNCTION represents one cycle

      OUTPUT should look like
      new_density = [[rho1lower, rho1, rho1upper], [rho2lower, rho2, rho2upper], ..., [rhoNlower, rhoN, rhoNupper]]
      '''

  r_profile = find_radius_profile(first_density, mass_profile) #RADIUS
  p_profile = find_pressure_profile(r_profile, mass_profile) #PRESSURE

  new_density = density_from_eos_profile(p_profile, temperature, eos_profile, **kwargs) #EQUATION OF STATE

  temp_profile = find_T_profile(p_profile, eos_profile, new_density, temperature[-1], **kwargs)

  return r_profile, p_profile, new_density, temp_profile

def create_mass_profile(mass_total, N, profile='constant'):
  if profile == 'constant':
    mass_profile = np.full(N, mass_total / N)
  elif profile == 'linear':
    mass_profile = np.linspace(mass_total / N, mass_total, N)
  # add more mass distribution profiles?
  return mass_profile

def create_temp_profile(T, N, profile='constant'):
  if profile == 'constant':
    T_profile = np.full(N, T)
  elif profile == 'linear':
    T_profile = np.linspace(T, 0, N) #this does not make sense right?
  return T_profile

def create_density_profile(rho, N, profile='constant'):
  if profile == 'constant':
    density_profile = np.full(N, rho)
  elif profile == 'linear':
    density_profile = np.linspace(rho, 0, N)
  return density_profile

################################################################################

def multi_iteration(starting_density, mass_total, N, T, eos_profile, mass_profile=None,
                    mass_distro_profile='constant', temp_distro_profile='constant',
                    density_distro_profile='constant', tolerance=1e-6, max_iter=20,
                    quiet=True, print_iter=2, **kwargs):
  if mass_profile==None:
    mass_profile = create_mass_profile(mass_total, N, profile=mass_distro_profile)
  else:
    mass_profile = np.array(mass_profile)

  if type(T) in [np.ndarray, list]:
    T = T
  else:
    T = create_temp_profile(T, N, profile=temp_distro_profile)

  if type(starting_density) in [np.ndarray, list]:
    rho = starting_density
  else:
    rho = create_density_profile(starting_density, N, profile=density_distro_profile)

  for iteration in range(max_iter):
    r_profile, p_profile, new_rho, temp_profile = one_cycle_var(mass_profile, rho, T, eos_profile, **kwargs)

    rel_diff = abs(new_rho[0] - rho[0]) / rho[0]

    if quiet == False: #and iteration >= max_iter-print_iter:
      print(f"Relative Änderung bei Iteration {iteration+1}:", rel_diff)

    # Abbruchbedingung
    if rel_diff < tolerance:
      if quiet == False:
        print("\nKonvergenz erreicht.")
      break

    # neues Profil übernehmen
    rho = new_rho.copy()

  if quiet == False:
    print("\nFinales Radiusprofil:")
    print(r_profile)

    print("\nFinales Druckprofil:")
    print(p_profile)

    print("\nFinales Dichteprofil:")
    print(new_rho)

    print("\nFinales Temperaturprofil:")
    print(temp_profile)

  return r_profile, p_profile, new_rho, temp_profile
